"""
QUICK START GUIDE - Web Scraping Project
Panduan cepat untuk memulai scraping
"""

print("=" * 70)
print("🚀 QUICK START - WEB SCRAPING PROJECT")
print("=" * 70)
print()
print("📁 File yang tersedia:")
print()
print("1️⃣  scraper_tokopedia.py")
print("   → Scraping produk dari Tokopedia")
print("   → Command: python3 scraper_tokopedia.py")
print()
print("2️⃣  scraper_google.py")
print("   → Scraping hasil pencarian Google")
print("   → Command: python3 scraper_google.py")
print()
print("3️⃣  scraper_universal.py")
print("   → Template universal untuk website apapun")
print("   → Command: python3 scraper_universal.py")
print()
print("4️⃣  scraper_google_maps.py ⭐ NEW!")
print("   → Scraping data bisnis dari Google Maps")
print("   → Command: python3 scraper_google_maps.py")
print()
print("=" * 70)
print("💡 CONTOH PENGGUNAAN:")
print("=" * 70)
print()
print("# Scraping Tokopedia")
print("$ python3 scraper_tokopedia.py")
print("  → Input keyword: laptop")
print("  → Input jumlah: 10")
print("  → Headless: n")
print()
print("# Scraping Google")
print("$ python3 scraper_google.py")
print("  → Input query: python tutorial")
print("  → Input jumlah: 10")
print("  → Headless: n")
print()
print("# Scraping Custom Website")
print("$ python3 scraper_universal.py")
print("  → Pilih: 1 (untuk contoh)")
print("  → Atau pilih: 2 (untuk custom URL)")
print()
print("# Scraping Google Maps (Bisnis di Cirebon)")
print("$ python3 scraper_google_maps.py")
print("  → Input kategori: restoran")
print("  → Input lokasi: Kabupaten Cirebon, Jawa Barat")
print("  → Input jumlah: 50")
print("  → Headless: n")
print()
print("=" * 70)
print("📊 OUTPUT:")
print("=" * 70)
print()
print("✅ Data disimpan dalam format JSON")
print("✅ Data disimpan dalam format CSV (untuk universal)")
print("✅ Filename include timestamp otomatis")
print()
print("Contoh output:")
print("  - tokopedia_laptop_20260131_132602.json")
print("  - google_python_tutorial_20260131_132602.json")
print("  - quotes_20260131_132602.json")
print("  - quotes_20260131_132602.csv")
print()
print("=" * 70)
print("🎯 TIPS:")
print("=" * 70)
print()
print("1. Jalankan tanpa headless mode dulu untuk melihat prosesnya")
print("2. Gunakan headless mode (y) untuk running di background")
print("3. Baca README.md untuk dokumentasi lengkap")
print("4. Cek file .gitignore untuk file yang di-ignore")
print("5. Semua scraper sudah include anti-detection settings")
print()
print("=" * 70)
print("✨ SELAMAT SCRAPING!")
print("=" * 70)
